version: '3.1'

services:
    wordpress:
        image: wordpress:php7.4-apache
        ports: 
            - 8081:80
        environment: 
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: root
            WORDPRESS_DB_NAME: wordpress
        links: 
            - mysql:mysql

    mysql:
        image: mysql:8.0.23
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - ~/docker/mysql-data:/var/lib/mysql

